### PR TITLE
Complete the Create Issue Modal issues

### LINKED ISSUE #215: [Feature Branch - Create Issue Modal] - submit button hangs if user forgets to select a repository
### Summary

**Requires that #123 be merged first.**

When a user forgets to select a repository before clicking the submit button, the button will hang.

The original conversation exists in the PR which adds the create issue modal. [Linked here](https://github.com/mattermost/mattermost-plugin-github/pull/123#issuecomment-598203967)

### Work from the `Feature-create-issue-modal` feature branch

This issue exists in a feature branch, not master.

To work on this issue:
* mention in this ticket that you would like to take the issue
* create a branch from the `FEATURE-create-issue-modal` branch https://github.com/mattermost/mattermost-plugin-github/tree/FEATURE-create-issue-modal
* submit PR against `FEATURE-create-issue-modal`

**UPDATE**  The Attach Message to GitHub Issue responses similarly.  The fix is to add validation to the two modals.

### LINKED ISSUE #216: [Feature Branch - Create Issue Modal] - no validation if title is left empty
### Summary
**Requires that https://github.com/mattermost/mattermost-plugin-github/pull/123 be merged first.**

If the user forgets to add a title to the ticket, validation should inform the user to fill out the title

The original conversation exists in the PR which adds the create issue modal. [Linked here](https://github.com/mattermost/mattermost-plugin-github/pull/123#issuecomment-598203967)

### Work from the `Feature-create-issue-modal` feature branch

This issue exists in a feature branch, not master.

To work on this issue:
* mention in this ticket that you would like to take the issue
* create a branch from the `FEATURE-create-issue-modal` branch https://github.com/mattermost/mattermost-plugin-github/tree/FEATURE-create-issue-modal
* submit PR against `FEATURE-create-issue-modal`

### LINKED ISSUE #217: [Feature Branch - Create Issue Modal] - Filter the list of repos to show only repos within specified organization
### Summary
**Requires that https://github.com/mattermost/mattermost-plugin-github/pull/123 be merged first.**

The request is to filter the repos, when creating an issue, to the organization's repos.  This is the current implementation for the attach comment to issue modal and should be matched for the create issue modal.

The original conversation exists in the PR which adds the create issue modal. [Linked here](https://github.com/mattermost/mattermost-plugin-github/pull/123#issuecomment-598203967)  The quoted text below is the relevant discussion from that PR.

> There are also a couple issues with the repository drop down.
> 
> When the the plugin is restricted to an Organization, the list of repos is not filter to show only the ones within that org. (There is a use case to be made for not doing this but at this point we should keep the logic consistent with attach functionality which does filter the repos when restricted to an org.)
> On related note - I'm curious how it's selecting the repos now? when I set this up on a server and don't restrict it to an Org, I can see my personal Org and the repos under my GutHub user but, not the public repos of Mattermost where I am also a member.
> @aaronrothschild may also have some thoughts on how this should work. If it's consistent with attach functionality, Any public repo where you're allowed to create issues would be searchable. Hence why 3. is so important.

> +1 on making it consistent with the Attach functionality. Otherwise, the search bar starts returning too may entries and it distracts the user.

### Work from the `Feature-create-issue-modal` feature branch

This issue exists in a feature branch, not master.

To work on this issue:
* mention in this ticket that you would like to take the issue
* create a branch from the `FEATURE-create-issue-modal` branch https://github.com/mattermost/mattermost-plugin-github/tree/FEATURE-create-issue-modal
* submit PR against `FEATURE-create-issue-modal`

### LINKED ISSUE #218: [Feature Branch - Create Issue Modal] - Repo dropdown search does not refine the selection
### Summary
**Requires that https://github.com/mattermost/mattermost-plugin-github/pull/123 be merged first.**

When a user trying to filter the repos by searching in the dropdown, the search does not work.

The original conversation exists in the PR which adds the create issue modal. [Linked here](https://github.com/mattermost/mattermost-plugin-github/pull/123#issuecomment-598203967)  The quoted text below is the relevant discussion from that PR.

> The drop down works but the search does not actually refine the selection. Regardless of what search term you put in, no data is removed from the drop down

### Work from the `Feature-create-issue-modal` feature branch

This issue exists in a feature branch, not master.

To work on this issue:
* mention in this ticket that you would like to take the issue
* create a branch from the `FEATURE-create-issue-modal` branch https://github.com/mattermost/mattermost-plugin-github/tree/FEATURE-create-issue-modal
* submit PR against `FEATURE-create-issue-modal`

### PR DESCRIPTION
**Pull request by jfrerich**
## Summary
This ticket resolves the remaining issues for the create-issue-modal feature that will be added to the master branch.  Please see the linked GH tickets in the Ticket Link Section.

Here is the commit message which lists the components that were added to the modal, as well as refactoring items. (ie. GitHubRepoSelector now uses ReactSelectSetting component)

**GitHubRepoSelector component**
  - now uses ReactSelectSetting component
  - made into its own component so it can be shared with the attach
    comment to issue modal, which needs a repo selector
  - uses the new validator component for validation in the
    ReactSelectSetting component
  - getReps()
    - called only once when componentDidMount is called
    - performs the client call to get the repos
  - pulled this.state variables initialization into its own initialState
    variable

**CreateIssueModal component**
  - holds selected repo state
  - calls validator component

**ReactSelectSetting component**
  - handles validation
  - handles reducing values when typing text in the search box
  - handles multiple select types automatically

**Setting component**
  - simple component to render the select and validation components in
    ReactSelectSetting

**Validator component**
  - contains addComponent function to attach an "isvalid" function to
    a ReactSelectSetting components. Passed down from parent
    CreateIssueModal
  - contains validate() function for computing if all registers
    componsents are valid

## Ticket Link
Resolved all of the following: 

Fixes #215 - [Feature Branch - Create Issue Modal] - submit button hangs if user forgets to select a repository
Fixes #216 - [Feature Branch - Create Issue Modal] - no validation if title is left empty
Fixes #217 - [Feature Branch - Create Issue Modal] - Filter the list of repos to show only repos within specified organization
Fixes  #218 - [Feature Branch - Create Issue Modal] - Repo dropdown search does not refine the selection

## Other Notes
commit #b664e25 was used as a starting point for grabbing the validator component.  This was the last commit before it was converted to TypeScript.

### CODE REVIEW

**Comment by jfrerich** [comment]
Thanks, @marianunez.  I agree the `ReactSelectSetting` component needs to be shareable so other plugins can just instantiate it.

**Comment by mickmister** [comment]
@marianunez @jfrerich

You may already be aware of it, but there is a [Common Components](https://community-daily.mattermost.com/core/channels/common-components) project, where one of the goals is to share components between webapp and plugins.

**Comment by jfrerich** [comment]
@mickmister, I wasn't aware of that channel.  Thanks for adding me.

File: webapp/src/components/github_repo_selector.jsx [hunk 1]
```diff
@@ -4,130 +4,67 @@
...
+        this.getRepos();
     }
 
-    handleGetRepoValue = () => {
-        return this.debouncedSearchRepo();
-    };
-
-    searchRepo = () => {
+    getRepos = () => {
         return Client.getRepositories().then((data) => {
```
Comment (mickmister) [inline webapp/src/components/github_repo_selector.jsx:36]: Can we move `getRepositories` into an action instead of directly accessing the `Client` in the component? This would require you to put this component in a folder, then `connect` it with an `index.js` file, like the [TimeSidebar](https://github.com/mattermost/mattermost-plugin-github/tree/master/webapp/src/components/team_sidebar) component. Then pass in the action as a prop using `mapDispatchToProps`.

The action won't end up storing the result in the redux store, but I think the code would be cleaner using props, as opposed to accessing `Client` directly.

File: webapp/src/components/react_select_setting.jsx [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+import ReactSelect from 'react-select';
+import AsyncSelect from 'react-select/async';
+import CreatableSelect from 'react-select/creatable';
+
+import Setting from 'components/setting';
+import {getStyleForReactSelect} from 'utils/styles';
+
+const MAX_NUM_OPTIONS = 100;
+
+export default class ReactSelectSetting extends React.PureComponent {
```
Comment (mickmister) [inline webapp/src/components/react_select_setting.jsx:16]: Any changes done to this component when porting from the Jira plugin?

File: webapp/src/components/setting.jsx [hunk 3]
```diff
@@ -20,24 +21,27 @@ export default class Setting extends React.PureComponent {
             inputId,
             label,
             required,
+            hideRequiredStar,
         } = this.props;
 
         return (
-            <div className='form-group'>
+            <div className='form-group less'>
+                {label &&
```
Comment (mickmister) [inline webapp/src/components/setting.jsx:29]: For readability. And add the closing paren

```suggestion
                {label && (
```

File: webapp/src/components/setting.jsx [hunk 4]
```diff
@@ -20,24 +21,27 @@ export default class Setting extends React.PureComponent {
...
-                {required && (
-                    <span
-                        className='error-text'
-                        style={{marginLeft: '3px'}}
-                    >
-                        {'*'}
-                    </span>
-                )}
+                }
+                {required && !hideRequiredStar &&
```
Comment (mickmister) [inline webapp/src/components/setting.jsx:37]: For readability. And add the closing paren

```suggestion
                {required && !hideRequiredStar && (
```

File: webapp/src/components/github_repo_selector.jsx [hunk 5]
```diff
@@ -4,130 +4,67 @@
...
+                    onChange={this.onChange}
+                    options={this.state.repoOptions}
                     isMulti={false}
-                    isClearable={true}
-                    defaultOptions={true}
-                    loadOptions={this.handleGetRepoValue}
-                    menuPortalTarget={document.body}
-                    menuPlacement='auto'
-                    styles={getStyleForReactSelect(this.props.theme)}
+                    key={'LT'}
```
Comment (mickmister) [inline webapp/src/components/github_repo_selector.jsx:62]: Doesn't really matter, but idk what `LT` means

```suggestion
                    key={'repo'}
```

File: webapp/src/components/modals/create_issue/create_issue.jsx [hunk 6]
```diff
@@ -38,6 +40,8 @@ export default class CreateIssueModal extends PureComponent {
             e.preventDefault();
         }
 
+        this.validator.validate();
```
[the remark this answers is not in the document]
Comment (jfrerich) [reply webapp/src/components/modals/create_issue/create_issue.jsx:43]: Gotcha. I don't need to check the statue of `repoValue`, just call the validate() function to verify it is valid.

File: webapp/src/components/github_repo_selector/github_repo_selector.jsx [hunk 7]
```diff
@@ -29,26 +30,18 @@ export default class GithubRepoSelector extends PureComponent {
...
-        });
-    };
-
     onChange = (name, newValue) => {
         this.props.onChange(newValue);
     };
 
     render() {
+        const repoOptions = this.props.yourRepos.map((item) => ({value: item.name, label: item.full_name}));
+        console.log('IN RENDER - OPTIONS', repoOptions);
```
Comment (jfrerich) [inline webapp/src/components/github_repo_selector/github_repo_selector.jsx:44]: will remove.

**Comment by jfrerich** [comment]
Hey @mickmister.  I just committed a change that adds the `getRepos` as an action and also added `yourRepos` property to redux.  Note that I have broken validation for the `GithubRepoSelector` component and will need to fix that before the PR is completed.  If the cause is glaring out to you, I'd appreciate the feedback.  Thanks again for the review!

File: webapp/src/components/github_repo_selector/github_repo_selector.jsx [hunk 8]
```diff
@@ -4,23 +4,24 @@
...
 const initialState = {
     invalid: false,
     error: null,
-    repoOptions: [],
 };
 
 export default class GithubRepoSelector extends PureComponent {
     static propTypes = {
-        required: PropTypes.bool,
+        yourRepos: PropTypes.any,
```
Comment (mickmister) [inline webapp/src/components/github_repo_selector/github_repo_selector.jsx:16]: From the definition of the reducer, it looks like this will always be present, and always be an array. Is this if block needed?
```suggestion
        yourRepos: PropTypes.array.isRequired,
```

File: webapp/src/components/github_repo_selector/github_repo_selector.jsx [hunk 9]
```diff
@@ -29,26 +30,18 @@ export default class GithubRepoSelector extends PureComponent {
     }
 
     componentDidMount() {
-        this.getRepos();
+        if (this.props.yourRepos) {
+            this.props.actions.getRepos();
```
Comment (mickmister) [inline webapp/src/components/github_repo_selector/github_repo_selector.jsx:34]: This doesn't make much sense to me. `props.yourRepos` should always be present already. Was there a case during development where this wasn't the case?

File: webapp/src/components/github_repo_selector/github_repo_selector.jsx [hunk 10]
```diff
@@ -57,13 +50,13 @@ export default class GithubRepoSelector extends PureComponent {
...
-                    options={this.state.repoOptions}
+                    options={repoOptions}
                     isMulti={false}
-                    key={'LT'}
+                    key={'repo'}
                     theme={this.props.theme}
                     addValidate={this.props.addValidate}
                     removeValidate={this.props.removeValidate}
-                    value={this.state.repoOptions.find((option) => option.value === this.props.value)}
+                    value={repoOptions.find((option) => option.value === repoOptions.value)}
```
Comment (mickmister) [inline webapp/src/components/github_repo_selector/github_repo_selector.jsx:59]: Found the issue :wink:

```suggestion
                    value={repoOptions.find((option) => option.value === this.props.value)}
```

Comment (jfrerich) [reply webapp/src/components/github_repo_selector/github_repo_selector.jsx:59]: I knew you would 😡 :smile:

File: webapp/src/components/github_repo_selector/github_repo_selector.jsx (hunk 8 above)
Comment (jfrerich) [reply webapp/src/components/github_repo_selector/github_repo_selector.jsx:16]: You are correct.  nice catch.

File: webapp/src/components/github_repo_selector/index.js [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+import {connect} from 'react-redux';
+import {bindActionCreators} from 'redux';
+
+import {getRepos} from '../../actions';
+
+import GithubRepoSelector from './github_repo_selector.jsx';
+
+function mapStateToProps(state) {
+    return {
+        yourRepos: state['plugins-github'].yourRepos,
```
[the remark this answers is not in the document]
Comment (jfrerich) [reply webapp/src/components/github_repo_selector/index.js:13]: All of the previously created `mapStateToProps` and `mapDispatchToProps` are using the hardcoded `plugins-github` instead of the `id` value from the manifest. 

I will keep as is for now and create a HW ticket to use the `id` for the manifest.

[the remark this answers is not in the document]
Comment (jfrerich) [reply webapp/src/components/github_repo_selector/index.js:13]: ticket created https://github.com/mattermost/mattermost-plugin-github/issues/238

and ticket picked up 2 minutes after posting :smile:

File: webapp/src/components/github_repo_selector/github_repo_selector.jsx (hunk 9 above)
Comment (jfrerich) [reply webapp/src/components/github_repo_selector/github_repo_selector.jsx:34]: I believe this was just left in from debugging and is not needed.  Removing
