### PR TITLE
[mm 509] Resolve OAuth bug with KVStore #509

### LINKED ISSUE #509: Resolve OAuth bug with KVStore
Details will be shared in the weekly MM-Demansol meeting. Update: the've been shared with Siba on the call.

### PR DESCRIPTION
**Pull request by sibasankarnayak**
fixed the logic of complete the oauth complete redirect

Fixes #509

### CODE REVIEW

File: server/plugin/api.go [hunk 1]
```diff
@@ -369,6 +401,13 @@ func (p *Plugin) completeConnectUserToGitHub(c *Context, w http.ResponseWriter,
 		MM34646ResetTokenDone: true,
 	}
 
+	appErr = p.API.KVDelete(stateToken)
+	if appErr != nil {
+		p.API.LogWarn("Failed to delete state token", "error", appErr.Error())
+		http.Error(w, "error deleting stored state", http.StatusBadRequest)
+		return
+	}
```
Comment (mickmister) [inline server/plugin/api.go:409]: This should be deleted from the KV store even if the OAuth process isn't successful, so I don't think it should move from where it originally was actually

File: server/plugin/api.go [hunk 2]
```diff
@@ -314,11 +314,43 @@ func (p *Plugin) completeConnectUserToGitHub(c *Context, w http.ResponseWriter,
 		return
 	}
 
-	appErr = p.API.KVDelete(stateToken)
-	if appErr != nil {
-		p.API.LogWarn("Failed to delete state token", "error", appErr.Error())
-		http.Error(w, "error deleting stored state", http.StatusBadRequest)
-		return
+	if strings.Contains(stateToken, githubTokenKey) {
```
Comment (mickmister) [inline server/plugin/api.go:317]: Shouldn't this instead be something like:

```go
if !strings.Contains(stateToken, githubTokenKey) {
    // deliver error response
    return
}
```

Then we continue on with the success path

File: server/plugin/api.go [hunk 3]
```diff
@@ -314,11 +314,43 @@ func (p *Plugin) completeConnectUserToGitHub(c *Context, w http.ResponseWriter,
...
+		html := `
+		<!DOCTYPE html>
```
Comment (mickmister) [inline server/plugin/api.go:319]: This HTML content is duplicated in this function. Since we're not supposed to write a success response at this part of the function, I think we should just remove this string from this part of the function.

Also, I think it makes sense to have a function `createHTMLResponse(message string) string` that will return this HTML string with the `message` placed inside of the `<p>` tag.

File: server/plugin/api.go [hunk 4]
```diff
@@ -314,11 +314,43 @@ func (p *Plugin) completeConnectUserToGitHub(c *Context, w http.ResponseWriter,
...
+			</head>
+			<body>
+			<p>Invalid Request. Please close this window.</p>
+			</body>
+			</html>
+		`
+		}
+
+		w.Header().Set("Content-Type", "text/html")
+		_, err := w.Write([]byte(html))
```
Comment (mickmister) [inline server/plugin/api.go:348]: We are now calling `w.Write` twice in this function. We should only be writing the response one time. This is true for all API requests for any plugin.

**Review by mickmister — CHANGES_REQUESTED** [review]
Thanks for implementing this @sibasankarnayak :+1: I have just a few requests

**Review by hanzei — COMMENTED** [review]
Should the code roughly follow the pattern from GitLab: https://github.com/mattermost/mattermost-plugin-gitlab/blob/de46ece13b8c9168c2beda3a8e9f0e6e7ed1e9f7/server/api.go#L132-L147

i.e. compare the stored state against the provided one first?

File: server/plugin/api.go (hunk 1 above)
Comment (sibasankarnayak) [reply server/plugin/api.go:409]: @mickmister keeping the code where it was is simply we are deleting it from KVStore with out even verifying the state and code Passed , 
i think if the state is some thing which passed is a uuid , once the oauth/complete API is access the previous state gets  
replaced , if we do without verify the details then we might loose the github user info and as well as sensitive information

File: server/plugin/api.go (hunk 2 above)
Comment (sibasankarnayak) [reply server/plugin/api.go:317]: @mickmister here we are accepting the state shouldn't have the `githubTokenKey` which is normal flow , if the state value consist of the `githubTokenKey` then this is an error case

Comment (mickmister) [reply server/plugin/api.go:317]: Okay so if the state has `githubTokenKey` then that's unwanted. So what _should_ we expect to be in `state`? Please take a look at the other related OAuth endpoints to see what we are setting  this value to.

File: server/plugin/api.go (hunk 1 above)
Comment (mickmister) [reply server/plugin/api.go:409]: We should first verify that `state` is the correct format that we would expect to receive in general, whether it matches what we have in the KV store. If it's incorrect, return. If it's the correct format, we should delete from the KV store before moving on, because this is supposed to be a one-time process.

**Comment by mickmister** [comment]
@hanzei Looking at the implementation you linked in the GitLab plugin, I'm not sure I like the fact that the KVStore key is equal to the `state`. It may not cause issues per se, but it seems weird that we are pulling from an arbitrary key specified in the request. 0/5 Instead, I would think we would have some sort of operation like this:

```go
state := r.URL.Query().Get("state")
kvKey := state + "_kvsuffix"
storedState, err := p.API.KVGet(kvKey)
// handle err

if storedState != state {
    // ...
}
```

File: server/plugin/api.go (hunk 4 above)
Comment (sibasankarnayak) [reply server/plugin/api.go]: Will follow the reference given by @hanzei  [here](https://github.com/mattermost/mattermost-plugin-github/pull/511#pullrequestreview-804104620)

File: server/plugin/api.go (hunk 3 above)
Comment (sibasankarnayak) [reply server/plugin/api.go]: will pass an error as `invalid state` in this case

File: server/plugin/api.go (hunk 2 above)
Comment (sibasankarnayak) [reply server/plugin/api.go:317]: @mickmister currently insteady of direct deleting the state from KVStore , we are checking the state first and then the code too is verified , immediately after that it is deleted , hope this will work fine

File: server/plugin/api.go (hunk 1 above)
Comment (sibasankarnayak) [reply server/plugin/api.go]: sure

**Comment by hanzei** [comment]
@mickmister Sure, adding a prefix for good sake sound good to me :+1:

File: server/plugin/api.go [hunk 5]
```diff
@@ -287,7 +287,7 @@ func (p *Plugin) connectUserToGitHub(c *Context, w http.ResponseWriter, r *http.
 		return
 	}
 
-	appErr := p.API.KVSetWithExpiry(state.Token, stateBytes, TokenTTL)
+	appErr := p.API.KVSetWithExpiry(state.Token+githubOauthKey, stateBytes, TokenTTL)
```
Comment (hanzei) [inline server/plugin/api.go:290]: Should be `githubOauthKey` a prefix, as the other keys in the store are?

Comment (mickmister) [reply server/plugin/api.go:290]: I agree with ☝️

**Comment by catalintomai** [comment]
@sibasankarnayak - can we address this sooner? The bitbucket one (and the bitbucket release) depend on this as well. Thanks.

**Review by hanzei — APPROVED** [review]

**Review by catalintomai — APPROVED** [review]

**Comment by dipak-demansol** [comment]
Tested the Pr and it **LGTM** still after discussion with Dylan i will add a final Update.

**Review by dipak-demansol — APPROVED** [review]
Tested with the Public(/Github connect) and Private(/Github connect private) Connection, Now The User is Not Disconnected. LGTM
