### PR TITLE
[GH-670] Fix issue: Code previews not working for branches

### LINKED ISSUE #670: Code previews only work for commit hashes, not for branches
A link pointing to .../master/... doesn't trigger the code preview for example.

A nice solution to prevent later changes would be to automatically look up the current commit the branch/tag points to and then saving that commit hash somehow to use for the preview.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Update code to show code preview for permalink with branch names

#### What to test?
- Getting code preview for permalinks with branch names

###### Steps to reproduce:
1. Connect your GitHub account
2. Open a file on  a GitHub repo
3. Click on any line *number* in the file
4. Copy the browser URL
5. Post the link in the channel

###### Expected behavior:
- You should get a preview of the code near that permalink.

#### Ticket Link
Fixes #670

### CODE REVIEW

**Comment by hanzei** [comment]
@raghavaggarwal2308 Can you please share a example permalink that now works?

**Comment by raghavaggarwal2308** [comment]
> @raghavaggarwal2308 Can you please share a example permalink that now works?

@hanzei Here is an example: https://github.com/mattermost/mattermost/blob/master/server/public/Makefile#L7

**Review by ayusht2810 — APPROVED** [review]

**Review by hanzei — CHANGES_REQUESTED** [review]
The feature doesn't seem to work with branches that are not `master`. e.g. https://github.com/mattermost/mattermost-plugin-github/blob/playwright-shared-repo/.gitmodules#L2 doesn't create a preview.

Can you please check what is going on?

**Comment by raghavaggarwal2308** [comment]
> The feature doesn't seem to work with branches that are not `master`. e.g. https://github.com/mattermost/mattermost-plugin-github/blob/playwright-shared-repo/.gitmodules#L2 doesn't create a preview.
> 
> Can you please check what is going on?

@hanzei I checked and found about the regex we are using to compare with the link and extract data is not accepting characters other than alphabets and numbers in the branch name. 
We can add any character in the branch on Github including `/`, due to which its very difficult to write a regex for this as the URL also contains forward slashes.  
The only solution we could think for this is to make some trade of and no support some characters like `\` here. We can mentions the same in the readme that the permalink preview will not work for branch names containing these characters.
Please let me your thoughts on this

**Comment by mickmister** [comment]
@raghavaggarwal2308 Let's support dashes and underscores here. It's okay if we don't support slashes because of the complications. We'll want to make sure there is no UX impact when the branch has a slash though. It should be as if it's not a link to a file, rather than failing to load it

File: server/plugin/permalinks.go [hunk 1]
```diff
@@ -94,11 +93,6 @@ func (p *Plugin) makeReplacements(msg string, replacements []replacement, ghClie
 	// iterating the slice in reverse to preserve the replacement indices.
 	for i := len(replacements) - 1; i >= 0; i-- {
 		r := replacements[i]
-		// quick bailout if the commit hash is not proper.
-		if _, err := hex.DecodeString(r.permalinkInfo.commit); err != nil {
-			p.client.Log.Warn("Bad git commit hash in permalink", "error", err.Error(), "hash", r.permalinkInfo.commit)
-			continue
-		}
```
[the remark this answers is not in the document]
Comment (Kshitij-Katiyar) [reply server/plugin/permalinks.go:101]: I think we can remove this as it is commit specific and our regex will handle all the other possible cases. I don't think there will be any implications here. @mickmister

File: server/plugin/permalinks_test.go [hunk 2]
```diff
@@ -354,13 +354,13 @@ func TestMakeReplacements(t *testing.T) {
 			},
 		},
 		{
-			name:   "bad commit hash",
-			input:  "start https://github.com/mattermost/mattermost-server/blob/badhash/app/authentication.go#L15-L22 lorem ipsum",
-			output: "start https://github.com/mattermost/mattermost-server/blob/badhash/app/authentication.go#L15-L22 lorem ipsum",
+			name:   "link with branch name",
+			input:  "start https://github.com/mattermost/mattermost-server/blob/master/app/authentication.go#L15-L22 lorem ipsum",
+			output: "start \n[mattermost/mattermost-server/app/authentication.go](https://github.com/mattermost/mattermost-server/blob/master/app/authentication.go#L15-L22)\n```go\ntype TokenLocation int\n\nconst (\n\tTokenLocationNotFound TokenLocation = iota\n\tTokenLocationHeader\n\tTokenLocationCookie\n\tTokenLocationQueryString\n)\n```\n lorem ipsum",
```
Comment (mickmister) [inline server/plugin/permalinks_test.go:359]: Does this test require connecting to the internet? Ideally this isn't the case, though idk if we have any sort of mocking in place for the requests to fetch code from GitHub. The other tests have a valid URL that points to this code, though this `master` branch one is a broken link. How does this test end up gathering this `TokenLocation` code for the test here?

- Working - https://github.com/mattermost/mattermost-server/blob/cbb25838a61872b624ac512556d7bc932486a64c/app/authentication.go#L15-L22
- Broken (used in this test) - https://github.com/mattermost/mattermost-server/blob/master/app/authentication.go#L15-L22

**Comment by Kshitij-Katiyar** [comment]
> @raghavaggarwal2308 Let's support dashes and underscores here. It's okay if we don't support slashes because of the complications. We'll want to make sure there is no UX impact when the branch has a slash though. It should be as if it's not a link to a file, rather than failing to load it

@mickmister https://github.com/mattermost/mattermost-plugin-github/blob/playwright-shared-repo/.gitmodules#L2 doesn't seem to work but in the different branch of the same repo i.e. `project-board-issue-workflow` seems to work https://github.com/mattermost/mattermost-plugin-github/blob/85c1cd46c155c7cd24974e40ba0ff78acc3c787d/.github/workflows/ci.yml#L8
Unable to understand why this is happening tho.  


> @raghavaggarwal2308 Let's support dashes and underscores here. It's okay if we don't support slashes because of the complications. We'll want to make sure there is no UX impact when the branch has a slash though. It should be as if it's not a link to a file, rather than failing to load it

@mickmister  Added the support for hyphen, Hope it aligns with your suggestion. Please look into it,

**Comment by Kshitij-Katiyar** [comment]
> The feature doesn't seem to work with branches that are not `master`. e.g. https://github.com/mattermost/mattermost-plugin-github/blob/playwright-shared-repo/.gitmodules#L2 doesn't create a preview.
> 
> Can you please check what is going on?

@hanzei @mickmister Working fine now.

File: server/plugin/permalinks_test.go (hunk 2 above)
Comment (Kshitij-Katiyar) [reply server/plugin/permalinks_test.go:359]: @mickmister This test does not require internet connectivity. we have to mock in the place of request. [mocking](https://github.com/mattermost/mattermost-plugin-github/blob/4f19c5cd2580342cdb965d8e1b0d7d8285d449db/server/plugin/permalinks_test.go#L435)

the link is used in the mock function to return the intended value so it works on a broken link too.
Can update the link here but it will lead to breaking other test cases.

**Comment by mickmister** [comment]
> > @raghavaggarwal2308 Let's support dashes and underscores here. It's okay if we don't support slashes because of the complications. We'll want to make sure there is no UX impact when the branch has a slash though. It should be as if it's not a link to a file, rather than failing to load it
> 
> @mickmister Added the support for hyphen, Hope it aligns with your suggestion.

@Kshitij-Katiyar I think underscores are commonly used in branch names too. Can we support branch names with underscores? Does it support capital letters as well? Maybe a unit test that tests using them together

**Comment by Kshitij-Katiyar** [comment]
> > > @raghavaggarwal2308 Let's support dashes and underscores here. It's okay if we don't support slashes because of the complications. We'll want to make sure there is no UX impact when the branch has a slash though. It should be as if it's not a link to a file, rather than failing to load it
> > 
> > 
> > @mickmister Added the support for hyphen, Hope it aligns with your suggestion.
> 
> @Kshitij-Katiyar I think underscores are commonly used in branch names too. Can we support branch names with underscores? Does it support capital letters as well? Maybe a unit test that tests using them together

@mickmister The existing regex already supported branches with an underscore, also in the last commit I have added the support for the hyphen.

**Review by mickmister — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
The above PR has been tested for the following scenarios:

- Tested the code preview for permalinks with branch names

The PR was working fine for the above mentioned condition, LGTM. Approved.

**Review by wiggin77 — APPROVED** [review]
